force-app/main/default/objects/Donations__c/Donations__c.object-meta.xml
<CustomObject>
    <label>Donations</label>
    <nameField>
        <displayFormat>{yy}{mm}-{000000}</displayFormat>
        <label>Donation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Donations__c/fields/Donation_Status__c.field-meta.xml
<CustomField>
    <fullName>Donation_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Donation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Cheque Returned</fullName>
            </value>
            <value>
                <fullName>Giro Rejected</fullName>
            </value>
            <value>
                <fullName>CC Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonationReconLWCController.cls
public with sharing class DonationReconLWCController {
    
    @AuraEnabled
    public static List<Donations__c> retrieveDonationList(String queryString){
        try {
            return Database.query(queryString);
        } catch (Exception err) {
            CustomException.printErrorInfo(err);
            throw new CustomException(err.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getSystemToday(){
        try {
            return Datetime.now().format('yyyy-MM-dd', 'Asia/Singapore');
        } catch (Exception err) {
            CustomException.printErrorInfo(err);
            throw new CustomException(err.getMessage());
        }
    }


    @AuraEnabled
    public static String updateDonation(List<Id> donationIdList, String donationStatus){
        try {
            List<Donations__c> donationToUpdateList = new List<Donations__c>();

            for(Id donationId : donationIdList){
                System.Debug('\n\ndonationId\n' + donationId);
                donationToUpdateList.add(new Donations__c(
                    id = donationId, 
                    Donation_Status__c = donationStatus,
                    Cleared_Datetime__c = donationStatus == 'Cleared' ? System.now() : null
                ));
            }

            
            Database.SaveResult[] donationsUpdateResult = Database.update(donationToUpdateList, false);

            String resultMessage = '';
            Integer successCount = 0;
            Integer failCount = 0;
            for(Database.SaveResult resultItem : donationsUpdateResult){
                System.Debug('\n\nresultItem\n' + resultItem);
                if(resultItem.isSuccess()){
                    successCount++;
                }
                else{
                    failCount++;
                }
            }

            
            if(successCount > 0){
                resultMessage += String.valueOf(successCount) + ' record';
                resultMessage += String.valueOf(successCount) =='1' ? ' was' : 's were';
                resultMessage += ' updated successfully.\n';
                
            }
            if(failCount > 0){
                resultMessage += String.valueOf(failCount) + ' record';
                resultMessage += String.valueOf(failCount) == '1' ? ' was' : 's were';
                resultMessage += ' failed to update.';
            }
            
            return resultMessage;
        } catch (Exception err) {
            CustomException.printErrorInfo(err);
            throw new CustomException(err.getMessage());
        }
    }
}